### ISSUE TITLE
nextflow.config does not accept absolute paths

### ISSUE THREAD

**Issue by mrbende** [SystemsGenetics/GEMmaker#178] opened 2020-05-19 17:37 UTC
When running GEMmaker using a HPC through nextflow, the config file does not accept absolute paths. The following error was received when including absolute paths in the config file...

```
reed@reed-VM:~/kube-runner$ nextflow -C nextflow.config kuberun SystemsGenetics/GEMmaker -v deepgtex-prp
Pod started: peaceful-jang
N E X T F L O W  ~  version 20.04.1
Launching `SystemsGenetics/GEMmaker` [peaceful-jang] - revision: 845d3f24f4 [master]
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [ff8cfaf36d]

===================================
 G E M M A K E R   P I P E L I N E
===================================

Workflow Information:
---------------------
  Project Directory:  /workspace/projects/SystemsGenetics/GEMmaker
  Launch Directory:   /workspace/reed
  Work Directory:     /workspace/reed/work
  Config Files:       [/workspace/projects/SystemsGenetics/GEMmaker/nextflow.config, /workspace/reed/nextflow.config]
  Container Engine:   null
  Profile(s):         standard


Input Parameters:
-----------------
  Remote fastq list path:     /workspace/reedbender/input//workspace/reedbender/input/SRA_IDs.txt
  Local sample glob:          /workspace/reedbender/input//workspace/reedbender/input/*_{1,2}.fastq


Quantification Tool Input:
--------------------------
  Use Hisat2:                 true
  Hisat2 Index Prefix:        GRCh38
  Hisat2 GTF File:            /workspace/reedbender/input/reference/GRCh38.gtf
  Hisat2 Index Directory:     /workspace/reedbender/input/reference/GRCh38.genome.Hisat2.indexed

  Use Kallisto:               false
  Kallisto Index File:        CORG.transcripts.Kallisto.indexed

  Use Salmon:                 false
  Salmon Index Directory:     CORG.transcripts.Salmon.indexed


Output Parameters:
------------------
  Output directory:           /workspace/reedbender/output
  Publish SRA:                false
  Publish downloaded FASTQ:   false
  Publish trimmed FASTQ:      false
  Publish BAM:                false
  Publish Gene Abundance:     false
  Publish GTF_GA:             false
  Publish RAW:                true
  Publish FPKM:               true
  Publish TPM:                true
  MultiQC:                    true
  Create GEM:                 true


Execution Parameters:
---------------------
  Queue size:                 4


Software Parameters:
--------------------
  Trimmomatic clip path:      null/files/fasta_adapter.txt
  Trimmomatic minimum ratio:  0.7

Error: GTF reference file for Hisat2 does not exist or is empty! Please Check that you have the proper references, that they are placed in the reference directory, and they are named properly.    
GEMmaker is missing the following file: '/workspace/reedbender/input/reference//workspace/reedbender/input/reference/GRCh38.gtf' (where '*' is the name of your organism)

 -- Check script '/workspace/projects/SystemsGenetics/GEMmaker/main.nf' at line: 122 or see '.nextflow.log' file for more details
```

**Comment by spficklin** [comment] 2020-05-19 21:20
Hi @mrbende .  Can you share the portion of your config file that has the reference genome setup?  We have a bit of a confusing way of specifying directories in GEMmaker which I think we need to adjust in the next release. I suspect the problem is just that it's confusing. If you can share, we can try to help out.

**Comment by spficklin** [comment] 2020-05-28 05:56
Hi @mrbende given our conversation earlier today I'm assuming you got past this, so I'm closing this out.  Please comment if you still have issues.

**Closed by spficklin** 2020-05-28 05:56 UTC
