### ISSUE TITLE
GEMmaker will not retry download_runs.py

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#238] opened 2021-07-07 19:42 UTC
No error is thrown if the run is failed to be downloaded. This prevents GEMmaker from retrying to download the run. 

`retrieve_sra.py` always returns error status of 0:
```
    # Return the exit code.
    sys.exit(0)
```

No indication of a failed run in the `out` file. Simply ignores runs which are not downloaded on first try and adds them to the `failed_runs` file.
```
[86/a6d5d2] process > download_runs (SRX1424254)     [100%] 474 of 474 ✔
[92/8bca91] process > fastq_dump (SRX1424254)        [100%] 459 of 459 ✔
```

**Suggested fix** 
`retrieve_sra.py` should throw error code which lets Nextflow know that a retry is needed. This should be also implemented for retrieving the meta data. This will prevent interuptions in downloads from preventing reads from being downloaded.

**Comment by spficklin** [comment] 2021-08-12 16:26
Hey @JohnHadish. This behavior is intentional.   The run is not actually ignored. It is written to a failed run file that is later incorporated into the failed run report so users can see which runs failed to work and why.  This was done because of the 26K Arabidopsis dateset... too many runs were failing because they didn't exist on NCBI or were corrupted and it was too time consuming to babysit all of those failures.   

If the failure is due to a temporary network issue and not with the run itself then you're right, the run will fail and GEMmaker will move on. In the meantime, the user can work around it by moving the corresponding file from the `work/GEMmaker/done` folder back into the `work/GEMmaker/stage` folder and restarting GEMmaker.   That's a bit annoying but is doable.  I think for now, we can add a section to the troubleshooting about how to deal with failed runs.

**Comment by spficklin** [comment] 2021-08-12 16:32
Correction:  copying the files from `work/GEMmaker/stage` won't restart the run.   There's actually not a good way to restart the run as you mention in the issue #237.   Since this issue and that one are so closely related. I'm going to close this one out because I think the problem is essentially the same.

**Closed by spficklin** 2021-08-12 16:32 UTC
Labels: documentation
