### ISSUE TITLE
ascp not working

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#91] opened 2019-01-30 17:18 UTC
@bentsherman reported the following when trying to use ascp

```Session Stop  (Error: Server aborted session: No such file or directory)```

Needs urgent fix

**Comment by bentsherman** [comment] 2019-01-30 17:59
@spficklin @biggstd On a related note, I found this in the prefetch help text:
```
$ prefetch --help
Usage:

...

  -t|--transport <value>           transport: one of: fasp; http; both. (fasp 
                                   only; http only; first try fasp (ascp), use 
                                   http if cannot download using fasp). 
                                   Default: both 
```

So apparently prefetch can use aspera or http in the backend? Might be a possible solution.

**Comment by biggstd** [comment] 2019-01-30 19:43
This error does not occur (on my local machine) with the test configuration we have. I am testing it on Kamiak as well, but since it is a bit backed up that could take some time.

This [documentation](https://support.asperasoft.com/hc/en-us/articles/216126818-Errors-4-50-No-such-file-or-directory-and-43-63-Cannot-collect-details-about-file-or-directory) seems to suggest that this is caused by us requesting a file that does not exist on the server.

There is also this from the same documentation:
> On Unix systems, check that you are not trying to transfer a special file, such as a symbolic link or a named pipe.

Although I don't think that pertains to our case.

@bentsherman Can you share more information (perhaps which sample) caused this error?

**Comment by bentsherman** [comment] 2019-01-30 20:09
@biggstd This bug actually first happened in one of the CI runs, you can see the log here:

https://travis-ci.org/SystemsGenetics/GEMmaker/builds/482948905?utm_source=github_status&utm_medium=notification

It's the most recent run on Stephen's PR. So it's the remote sample in the example that fails. I agree that the error seems to suggest that the SRA file can't be found, the odd thing is that it just started happening. I believe I'm having this issue with the Ath runs as well but it's been a few days since I last checked that.

**Comment by bentsherman** [comment] 2019-02-05 12:59
This error doesn't seem to happen anymore on the example run... if it works on Palmetto later today then I'm going to close this issue.

**Comment by bentsherman** [comment] 2019-02-13 15:59
I've been running Ath 11-20 on Palmetto without any problems from ascp, closing.

**Closed by bentsherman** 2019-02-13 15:59 UTC
Labels: URGENT, bug
