### ISSUE TITLE
SRX sample.csv  files aren't filtered to be a unique list

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#92] opened 2019-01-30 21:48 UTC
While running the Ath 26K experiment I noticed that in the sample CSV files stored in the `work/GEMmaker/[stage|process|done]` directories, if an experiment has more than one run the list of runs may have duplicates.  For example.  The SRX1734902.sample.csv file has these contents:

>"SRX1734902","SRR3463180 SRR3463181 SRR3463182 SRR3463183 SRR3463187 SRR3463186 SRR3463185 SRR3463184 SRR3463180 SRR3463181 SRR3463182 SRR3463183 SRR3463184 SRR3463185 SRR3463186 SRR3463187 SRR3463180 SRR3463181 SRR3463182 SRR3463183 SRR3463184 SRR3463185 SRR3463186 SRR3463187 SRR3463180 SRR3463181 SRR3463182 SRR3463183 SRR3463184 SRR3463185 SRR3463186 SRR3463187 SRR3463180 SRR3463181 SRR3463182 SRR3463183 SRR3463184 SRR3463185 SRR3463186 SRR3463187 SRR3463180 SRR3463181 SRR3463182 SRR3463183 SRR3463184 SRR3463185 SRR3463186 SRR3463187 SRR3463180 SRR3463181 SRR3463182 SRR3463183 SRR3463184 SRR3463185 SRR3463186 SRR3463187 SRR3463180 SRR3463181 SRR3463182 SRR3463183 SRR3463184 SRR3463185 SRR3463186 SRR3463187 SRR3463188 SRR3463189 SRR3463190 SRR3463191 SRR3463192 SRR3463193 SRR3463188 SRR3463189 SRR3463190 SRR3463191 SRR3463192 SRR3463193 SRR3463188 SRR3463189 SRR3463190 SRR3463191 SRR3463192 SRR3463193 SRR3463188 SRR3463189 SRR3463190 SRR3463191 SRR3463192 SRR3463193 SRR3463188 SRR3463189 SRR3463190 SRR3463191 SRR3463192 SRR3463193 SRR3463188 SRR3463189 SRR3463190 SRR3463191 SRR3463192 SRR3463193","remote"

This experiment has 14 samples but some are repeated multiple times.  I'm thinking this may cause SRR files to download multiple times.

**Comment by bentsherman** [comment] 2019-01-31 20:48
I think it's being caused by `retrieve_sra_metadata.py`, are you using your branch with the fix you made? I'm looking at that version of the script and I think it's actually writing out SRR IDs multiple times. Seems to be related to #86 -- the script downloads the entire SRX metadata for each run, which is redundant when the input has multiple runs from the same experiment.

If you're using your issue-88 branch then I think I can fix this issue pretty easily.

**Comment by bentsherman** [comment] 2019-02-05 12:56
Resolved by #90

**Closed by bentsherman** 2019-02-05 12:56 UTC
Labels: bug
