### ISSUE TITLE
Organize process parameters.

### ISSUE THREAD

**Issue by biggstd** [SystemsGenetics/GEMmaker#46] opened 2018-11-07 05:14 UTC
Right now we are implementing process directives and arguments in an inconsistent way.  

To consider:

+ Are modules general enough be hard coded in `main.nf`?
+ Should labels ("multithreaded") be replaced with per-process options?
+ Some parts of the config file reference itself ("execution").

I will try to remove some of this redundancy and make things consistent.

**Comment by bentsherman** [comment] 2018-11-07 22:57
- We should probably make constants for the module names in the config file, that would give the user much better control over their choice of modules
- I think the `multithreaded` label should be left as is because it captures all of the processes that have multithreading capabilites. You could make them per-process options but then those options would be more obscure. Considering that it's a major performance parameter I think it's better to keep it prominent, and I don't think it's likely that the user will need to specify different levels of multithreading per process. Also I kind of need that label right now for things to work well on Palmetto.
- The params section is designed to be used by other config scopes like trace and profile, that is a feature not a bug. In particular, `params.execution` is used by both the profile section and `main.nf`. I would leave that section as is too.

**Comment by spficklin** [comment] 2018-12-18 00:10
Some of this issue should be fixed by Tyler's new Docker images .... one for each software + version.

**Closed** 2019-01-15 19:49 UTC
Labels: discussion
