### ISSUE TITLE
Gemmaker cannot pull SRA datasets

### ISSUE THREAD

**Issue by feltus** [SystemsGenetics/GEMmaker#214] opened 2021-04-13 17:16 UTC
Hi.

My students and I have used GEMmaker in the past weeks, but it appears to be broken at the SRA download stage.  Even the test dataset is broken with this command line;

`nextflow run main.nf -profile standard -with-singularity -with-report -with-timeline`

Final error:
```
Error executing process > 'download_runs (SRX218012)'

Caused by:
  Process `download_runs (SRX218012)` terminated with an error exit status (1)

Command executed:

  ids=`echo SRR649944 | perl -p -e 's/[\[,\]]//g' | perl -p -e 's/\s*$//' | perl -p -e 's/\s+/,/g'`
  retrieve_sra.py $ids

Command exit status:
  1

Command output:
  Getting download paths for sample: SRR649944
  ['srapath', '--protocol', 'fasp', '--json', 'SRR649944']
  Error: RC(rcVFS,rcQuery,rcExecuting,rcItem,rcNotFound)

Command error:
  
  Traceback (most recent call last):
    File "/home/student/temp44/GEMmaker/bin/retrieve_sra.py", line 192, in <module>
      ec = download_samples(run_ids)
    File "/home/student/temp44/GEMmaker/bin/retrieve_sra.py", line 139, in download_samples
      urls = get_sample_url(run_id)
    File "/home/student/temp44/GEMmaker/bin/retrieve_sra.py", line 66, in get_sample_url
      res = json.loads(res['stdout'])
    File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
      raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Work dir:
  /home/student/temp44/GEMmaker/work/2e/a0352b8e6995289e02de144e449065

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Comment by bentsherman** [comment] 2021-04-16 17:22
@spficklin Feltus and Cole and I dug into this issue today and I think we found the root cause in `retrieve_sra.py`. You can replicate this error by simply running nextflow out of the box on the example data, and it happens on both master and develop.

Basically srapath is failing with exit code 1 and this error, which you can see in Feltus' error log:
```
Error: RC(rcVFS,rcQuery,rcExecuting,rcItem,rcNotFound)
```

The problem is that srapath is printing this message to stdout, which causes this code to fail:
```
    # First try if there is an aspera path.
    p = subprocess.Popen(["srapath", "--protocol", "https", "--json", run_id],
                         stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    res = process_wait(p)
    res = json.loads(res['stdout'])
```

So `get_sample_url()` doesn't check to see if srapath failed with fasp protocol, it just tries to parse stdout as json no matter what. We need to add some proper error checking here.

I'm not sure why this worked for months and then stopped working. I'm wondering if NCBI updated the HTTP responses of their API in such a way that messed up what this script was expecting.

**Comment by spficklin** [comment] 2021-04-16 17:50
Hey @bentsherman, just some additional info.  We don't have this problem here. We've not experienced this error and I've been running the CORG data using the current version of GEMamker with no problems.  And I've not had this issue with any of the testing I've done to upgrade GEMmaker to nf-core, nor for the large Arabidopsis work that's going on too.

Also, I have made recent changes to the `retrieve_sra.py` script  in the `develop` branch.  It sounds like those fixes won't address this issue but just wanted to point out there are differences in that script in the current dev version.

**Comment by bentsherman** [comment] 2021-04-16 18:10
@spficklin It looks like the code block I referenced is current to master, develop, and nf-core. Currently it says the retrieve_sra.py on the develop branch hasn't been updated in 23 days. So I'm not sure what changes you're referring to.

I'm starting to suspect that the problem lies with how srapath is executing. Maybe Palmetto and the praxis VM just both happen to have some system-level issue with the NCBI API that causes this sample to fail. But ultimately, the problem is that retrieve_sra.py isn't handling this error properly.

Since you aren't seeing this error on Kamiak I will test a fix for Palmetto and submit a PR. I'll just add some error checking that should not affect execution on Kamiak.

**Comment by spficklin** [comment] 2021-04-16 18:57
Yes, it's probably those that were done 23 days ago.  There was a bit of a logic bug with it that was preventing Aspera from being used properly.

Thanks for working on the fix!

**Comment by bentsherman** [comment] 2021-04-16 19:19
@spficklin The code for getting the https path seems completely off. It is calling srapath with `-P` instead of `--json`, which returns just the path instead of the json object, but then it tries to parse the stdout as if it were the json object. Also there is a typo, 'response' instead of 'responses'.

https://github.com/SystemsGenetics/GEMmaker/blob/develop/bin/retrieve_sra.py#L78

What is going on with this code? The https route must not get called very often because I don't know how it wouldn't fail.

**Comment by bentsherman** [comment] 2021-04-16 19:25
@spficklin Sorry for that burst of frustration. I think the https code just hasn't been touched in a while and probably just doesn't get called very often in our recent workloads. I have fixed the problems I found so I will include that as a bonus in my PR.

**Comment by bentsherman** [comment] 2021-04-17 13:08
@feltus A permanent fix has been merged into GEMmaker. Simply tell your students to just use the develop branch:
```
git checkout develop
git pull
```

**Closed by bentsherman** 2021-04-17 13:08 UTC

**Comment by feltus** [comment] 2021-04-17 13:21
Thank you all!
