### ISSUE TITLE
Use ascp instead of sratoolkit in 'fastq_dump' process

### ISSUE THREAD

**Issue by cwytko** [SystemsGenetics/GEMmaker#47] opened 2018-11-08 18:27 UTC
As stated here https://www.ncbi.nlm.nih.gov/books/NBK158899/#SRA_download.when_to_use_a_command_line and here https://www.ncbi.nlm.nih.gov/books/NBK158899/#SRA_download.performance_comparison_of_f it will be better to use ascp instead of sratoolkit to download the runs.

**Comment by spficklin** [comment] 2018-11-08 19:03
I think we probably should swap this out for our v1.0 release as we had a discussion in our meeting on 11/5 /2019 about abusing NCBI's web services.  But as we have a working GEMmaker right now I would say we bump this fix to the bottom of our priority list and try to get it into a v1.0 release.

**Comment by spficklin** [comment] 2018-11-08 19:05
Oops I think I'm confusing our metadata requests to NCBI web services with this issue.  But this is still a fix we should do and if we can get it into the v1.0 release then I would say we do it if time permits. I'll mark this as low-priority.

**Comment by bentsherman** [comment] 2018-12-21 19:44
The SRA toolkit also introduced a tool called `fasterq-dump` in version 2.9.1 which apparently is just an improved version of `fastq-dump`, and it supports multithreading. Might be another good option.

**Comment by spficklin** [comment] 2018-12-26 22:47
Oh good to know!

**Comment by spficklin** [comment] 2018-12-29 01:46
So I picked up on this where Tyler left off.  Aspera 3.9.1 is the most recent version but it seems to be missing the SSH key needed.  I had to add a 3.8.1 version to GEMmaker which does have the key. But unfortunately, you can't install Aspera as the root user. It must be installed as the `gemdocker` user.  However, when you run GEMmaker with the docker profile it does not run as the `gemdocker` user but as the user running the workflow so `ascp` does not work.   

Beause we're short on time I took this off the v1.0 release project/milestones.  I've committed as far as  I could get on the `issue-47-aspera_integration` branch if someone wants to pick it up and make it work.

**Comment by bentsherman** [comment] 2018-12-29 17:15
I would like to take a look at this once I am back online since this might be a workaround for me. I'll see what I can do about the docker issue.

**Comment by bentsherman** [comment] 2019-01-07 19:46
So I checked out the aspera branch a few days ago, confirmed that you can't install aspera as the root user. One potential solution is to install aspera and then move the `.aspera` to `/root`, the home directory of the root user. It looks like all of the installed files are in that directory. I will try this out.

**Comment by spficklin** [comment] 2019-01-09 22:52
Fixed as per @bentsherman's PR.

**Closed by spficklin** 2019-01-09 22:53 UTC
Labels: discussion, enhancement
