### ISSUE TITLE
Documentation needs more info regarding profiles/docker/singularity

### ISSUE THREAD

**Issue by mtmcgowan** [SystemsGenetics/GEMmaker#120] opened 2019-07-23 21:24 UTC
I think there needs to be more info about how to set up a profile for running Gemmaker locally with docker or singularity out-of-the-box (and more explanation for profiles in general).

There seem to be two ways to run Gemmaker with docker:
1) specify a profile with docker.enabled = true (but there is also another docker scope setting in the config on line 102, which causes confusion)
2) specify in the command line -with-docker (which is not explained in the Gemmaker documentation)

The documentation for profiles currently points to the Nextflow documentation, which is not very effective for helping the average user who will have little to no experience with Nextflow. Currently, this step leads to information overload when trying to determine which parameters listed in the Nextflow documentation are relevant to Gemmaker. They probably will not want to read everything about Nextflow profiles to simply get Gemmaker running. I think creating a few out-of-the-box profiles for running Gemmaker locally with docker/singularity would help. Then the documentation could have a table showing what these basic profiles do.

**Comment by JohnHadish** [comment] 2019-07-30 21:39
I agree, this is confusing.

I propose completely eliminating the command line arguments `-with-singularity` and `-with-docker`.
They can be replaced with an argument in the `nextflow-config` rather easily. 

In addition to making this less confusing, this will assist with reproducibility of runs by saving this information in the `nextflow-config`

**Comment by JohnHadish** [comment] 2019-07-30 21:40
Thoughts? @spficklin @bentsherman

**Comment by bentsherman** [comment] 2019-08-21 23:53
Sorry for taking so long to get back to you on this. We can definitely add some basic examples for eqch way to run GEMmaker. I simply pointed to nextflow docs at first because it was easier and I didn't want to duplicate information. Now that the various use cases are clearer to me I can add some examples.

It's true that you can specify docker / singularity through the command line or the config file. That's just a flexibility thing -- different users have different requirements in the way they use nextflow. I still prefer to use the commqnd line method, because it's quicker to add / remove a command line flag than to edit a config file. And it's easier to automate.

But let me make a PR with some of these documentation changes and see if that clears things up.

**Comment by bentsherman** [comment] 2019-08-22 19:39
PR is ready for review.

A clarification on the config file: the `docker` and `singularity` scopes in the config file simply define how docker and singularity behave __when they are enabled__, not whether they are actually enabled. This is important because users may prefer to use `-with-docker` or `-with-singularity` instead of using a profile, and in that case the docker / singularity config scopes need to be defined in the main body of the config file. The `report`, `timeline`, and `trace` scopes work exactly the same way, except they are enabled by default.

**Comment by spficklin** [comment] 2019-09-17 18:36
This seems to be done and PR merged.  closing....

**Closed by spficklin** 2019-09-17 18:36 UTC
